### ISSUE TITLE
We might have missed a low hanging fruit naming-wise

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Pet-Clinic-GilmoreDevs#43]
https://github.com/gfa-cc-after/Pet-Clinic-GilmoreDevs/tree/main/backend/src/main/java/com/greenfoxacademy/backend/dtos

We should unify this in my opinion. We can even create subpackages if needed.

![image](https://github.com/user-attachments/assets/3d672012-70f6-429d-88f6-f1ba24faeca1)

**Comment by ramesz6** [comment]
you mean like Login/Register subpackage?

**Comment by markkovari** [comment]
I meant RegisterUerRequest should be RegisterRequestDto, but yes we can separate by request/response or by login/register too.
