### ISSUE TITLE
We should decide which frontend http client to use

### ISSUE THREAD

**Issue by markkovari** [gfa-cc-after/Pet-Clinic-GilmoreDevs#56]
We are using `fetch` and `axios` in different pages/components. This might lead to inconvenient inconsistencies, we should pick one and stick with it.

And by the way if we create an "api" which is one module (place) with the requests, it will be easier to change/replace later.

**Comment by deepanshu2711** [comment]
We can create a folder called api in frontend and export all required data fetching logic from there . We should stick with axios as it is easier to implement and more efficient i guess

can you assign this work to me ?

**Comment by markkovari** [comment]
Hey @deepanshu2711 appreciate your reaction and proposal, although this is a class group assignment and have to decline your offer. Have a good day and keep up being proactive

**Comment by Hsbalazs** [comment]
We use axios generally.
